### ISSUE TITLE
Images in footer component are being imported from public folder 

### ISSUE THREAD

**Issue by ShafayetAhmad** [MdAbdullahIbnNoor/prerok-global#39]
assets in the footer component or other components are being imported and used from the public folder directly which is against the convention. Instead, we should use 3rd party service like IMGBB or keep our assets in the src folder.

@tamim6421 vai can you fix that by tomorrow?

**Comment by tamim6421** [comment]
I am ready to do that.

**Comment by tamim6421** [comment]
Ok, I done this .
