### ISSUE TITLE
Shipping Section Development

### ISSUE THREAD

**Issue by ShafayetAhmad** [MdAbdullahIbnNoor/prerok-global#43]
### Objective
The objective of this issue is to design and develop the shipping section of the website, incorporating features such as creating a shipping/order placement, knowing rates/pricing, scheduling and managing pickups, and generating packaging and shipping labels.

#### 1. Create Shipping/Place an Order
- [ ] Design and implement the user interface for placing a shipping order.
- [ ] Develop backend API endpoints for processing shipping orders.
- [ ] Integrate the frontend with backend to enable users to place shipping orders.

#### 2. Know Rates/Pricing
- [ ] Design a form with multiple input fields for users to inquire about shipping rates.
- [ ] Input fields should include departure country, destination country, product type, weight, etc.
- [ ] Implement backend logic to calculate shipping rates based on the provided information.
- [ ] Display the calculated rates to the user.

#### 3. Algorithm/Basic Math for Pricing Section
- [ ] Define and document the algorithm for calculating shipping rates.
- [ ] Consider factors such as distance, weight, product type, and any additional charges.
- [ ] Implement and test the algorithm to ensure accurate pricing calculations.

#### 4. Schedule and Manage Pickups
- [ ] Design a user-friendly interface for scheduling and managing pickups.
- [ ] Implement backend functionality to handle pickup requests.
- [ ] Integrate pickup scheduling with the user account system.

#### 5. Packaging and Shipping Label Generation
- [ ] Create a feature for users to input packaging details.
- [ ] Implement logic for generating shipping labels based on the provided information.
- [ ] Integrate label generation with the overall shipping process.

### Additional Considerations
- [ ] Ensure proper validation of user inputs for all forms.
- [ ] Implement security measures to protect sensitive information.
- [ ] Consider implementing notifications for users on the status of their shipments.

### Deadline
This issue should be completed by [insert deadline here].

### Notes
- To be completed on or before 31/01/2024

**Comment by ShafayetAhmad** [comment]
@MdAbdullahIbnNoor vai could you manage to implement this section by Wednesday along with @Shanto93 vai and @abir-exe vai?

**Comment by MdAbdullahIbnNoor** [comment]
I will try my best to do this section
