### ISSUE TITLE
User Accounts and Profile Section Development

### ISSUE THREAD

**Issue by ShafayetAhmad** [MdAbdullahIbnNoor/prerok-global#44]
### Objective
The objective of this issue is to design and develop the user accounts and profile sections, providing users with a secure and personalized experience.

#### 1. User Registration and Authentication
- [x] Implement user registration functionality.
- [x] Develop secure authentication mechanisms.
- [x] Integrate user registration and login forms into the frontend.

#### 2. User Profile Interface
- [x] Design a user-friendly interface for user profiles.
- [ ] Include sections for personal details, shipping history, and preferences.
- [x] Allow users to edit and update their profile information.

#### 3. Secure Login System
- [x] Implement a secure login system with password protection.
- [ ] Enable password recovery mechanisms (e.g., email verification or reset).

#### 4. Customer Accounts
- [ ] Develop customer accounts for managing shipments and preferences.
- [ ] Associate shipping orders and history with individual customer accounts.

#### 5. Profile Photo and Avatar
- [ ] Allow users to upload and manage profile photos or avatars.
- [ ] Integrate with a storage solution for handling user profile images.

#### 6. Social Media Integration 
- [x] Consider integrating social media login options for user convenience.
- [ ] Implement necessary OAuth mechanisms if social media login is included.

#### 7. User Preferences and Settings
- [ ] Create a section for users to customize their preferences and settings.
- [ ] Implement backend logic to store and apply user preferences.

### To Do
- [ ] Implement role-based access controls if there are different user roles (e.g., admin, regular user).
- [ ] Ensure all sensitive user information is securely stored and transmitted.
- [ ] Implement proper error handling and validation for user inputs.

### Deadline
This issue should be completed by 31/01/2024.

**Comment by ShafayetAhmad** [comment]
@tamim6421 vai and @mahmudulturan you need to help me complete this by next Wednesday

**Comment by mahmudulturan** [comment]
Okay I will do it within 31 January.
